Repository WDTT-CodingClub/NBDream, pull requests merged in 2024-07, with the labels that each got.

#206 Fix: 댓글 프사 기본 토봇, crop 적용
  feature/main/src/main/java/kr/co/main/community/detail/BulletinDetailScreen.kt
  feature/main/src/main/java/kr/co/main/ui/DreamMainPostCard.kt
Labels: 🐞 bug, 🤖 android

#205 Feature/accountbook
  feature/main/src/main/java/kr/co/main/accountbook/content/AccountBookContent.kt
  feature/main/src/main/java/kr/co/main/accountbook/create/AccountBookCreateRoute.kt
  feature/main/src/main/java/kr/co/main/accountbook/main/AccountBookBottomSheet.kt
  feature/main/src/main/java/kr/co/main/accountbook/main/AccountBookRoute.kt
  feature/main/src/main/java/kr/co/main/accountbook/model/AccountBookModel.kt
  feature/main/src/main/java/kr/co/main/accountbook/model/DateRangeOption.kt
Labels: 🤖 android, 🎨design

#208 영농일지 작성/수정/삭제 완성
  core/data/src/main/java/kr/co/data/mapper/DiaryMapper.kt
  core/data/src/main/java/kr/co/data/model/data/calendar/DiaryData.kt
  core/data/src/main/java/kr/co/data/repository/DiaryRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/source/remote/DiaryRemoteDataSource.kt
  core/domain/src/main/java/kr/co/domain/entity/DiaryEntity.kt
  core/domain/src/main/java/kr/co/domain/entity/type/WorkDescriptionType.kt
  core/domain/src/main/java/kr/co/domain/repository/DiaryRepository.kt
  core/domain/src/main/java/kr/co/domain/usecase/calendar/DeleteDiaryUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/calendar/GetDiaryDetailUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/calendar/UpdateDiaryUseCase.kt
  core/remote/src/main/java/kr/co/remote/DiaryRemoteDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/mapper/calendar/DiaryRemoteMapper.kt
  core/remote/src/main/java/kr/co/remote/model/request/calendar/UpdateDiaryRequest.kt
  core/remote/src/main/java/kr/co/remote/model/response/calendar/DiaryListResponse.kt
  feature/main/src/main/java/kr/co/main/calendar/common/content/DiaryContent.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addDiaryScreen/AddDiaryScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addDiaryScreen/AddDiaryViewModel.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/CalendarScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/DiaryTab.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/ScheduleTab.kt
  feature/main/src/main/java/kr/co/main/model/calendar/DiaryModel.kt
  feature/main/src/main/java/kr/co/main/my/setting/crop/MyPageCropSelectRoute.kt
Labels: 🤖 android, 🎨design

#209 Fix: 글 작성화면 텍스트박스 늘어나게 변경
  feature/main/src/main/java/kr/co/main/community/writing/BulletinWritingScreen.kt
Labels: 🐞 bug, 🤖 android

#212 Fix: 장부 아이템 없을 때 그래프 안 보이는 부분 수정 및 코드 정리
  feature/main/src/main/java/kr/co/main/accountbook/content/AccountBookContent.kt
  feature/main/src/main/java/kr/co/main/accountbook/create/AccountBookCreateRoute.kt
  feature/main/src/main/java/kr/co/main/accountbook/main/AccountBookRoute.kt
Labels: 🤖 android

#210 Fix: 글 작성화면 imePadding, navigationBarsPadding
  feature/main/src/main/java/kr/co/main/community/writing/BulletinWritingScreen.kt
Labels: 🐞 bug, 🤖 android

#213 Feature/community
  feature/main/src/main/java/kr/co/main/community/writing/BulletinWritingScreen.kt
  feature/main/src/main/java/kr/co/main/community/writing/BulletinWritingViewModel.kt
Labels: 🤖 android

#214 Refactor: DreamDialog 사용
  feature/main/src/main/java/kr/co/main/accountbook/content/AccountBookContent.kt
  feature/main/src/main/java/kr/co/main/accountbook/create/AccountBookCreateRoute.kt
  feature/main/src/main/java/kr/co/main/accountbook/main/AccountBookGraph.kt
  feature/main/src/main/java/kr/co/main/accountbook/main/AccountBookRoute.kt
  feature/main/src/main/java/kr/co/main/accountbook/model/AlertDialog.kt
Labels: 🤖 android, 🛠️ refactor

#220 Feature/fcm
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/wdtt/nbdream/service/DreamFirebaseMessagingService.kt
  build.gradle.kts
  core/data/src/main/java/kr/co/data/mapper/AlarmStatusMapper.kt
  core/data/src/main/java/kr/co/data/model/data/AlarmStatusData.kt
  core/data/src/main/java/kr/co/data/repository/FcmRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/source/remote/FcmRemoteDataSource.kt
  core/domain/src/main/java/kr/co/domain/entity/AlarmStatusEntity.kt
  core/domain/src/main/java/kr/co/domain/repository/FcmRepository.kt
  core/remote/src/main/java/kr/co/remote/FcmRemoteDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/di/RemoteModule.kt
  core/remote/src/main/java/kr/co/remote/mapper/AlarmStatusRemoteMapper.kt
  core/remote/src/main/java/kr/co/remote/model/request/fcm/AlarmUpdateRequest.kt
  core/remote/src/main/java/kr/co/remote/model/request/fcm/FcmSendRequest.kt
  core/remote/src/main/java/kr/co/remote/model/request/fcm/FcmTokenRequest.kt
  core/remote/src/main/java/kr/co/remote/model/response/fcm/GetAlarmStatusResponse.kt
  feature/main/src/main/java/kr/co/main/accountbook/model/DatePickerDialog.kt
  gradle/libs.versions.toml
Labels: 🤖 android, ✨ feat

#221 캘린더 화면 뷰 모델 리팩토링
  core/domain/src/main/java/kr/co/domain/usecase/calendar/GetLocalUserCropsUseCase.kt
  feature/main/src/main/java/kr/co/main/calendar/common/AddScreenCenterTopAppBar.kt
  feature/main/src/main/java/kr/co/main/calendar/common/content/CalendarContentDropDownMenu.kt
  feature/main/src/main/java/kr/co/main/calendar/common/content/DiaryContent.kt
  feature/main/src/main/java/kr/co/main/calendar/common/content/ScheduleContent.kt
  feature/main/src/main/java/kr/co/main/calendar/common/dialog/CalendarDialogState.kt
  feature/main/src/main/java/kr/co/main/calendar/common/dialog/CalendarDialogWithToast.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addDiaryScreen/AddDiaryScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addDiaryScreen/AddDiaryViewModel.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addScheduleScreen/AddScheduleScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/addScheduleScreen/AddScheduleViewModel.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/CalendarScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/CalendarScreenViewModel.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/CalendarYearMonthBottomSheet.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/DiaryTab.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/ScheduleTab.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/calendar/CalendarDateRow.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/calendar/DiaryCalendar.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/calendar/FarmWorkCalendar.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/calendarScreen/calendar/ScheduleCalendar.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/farmWorkInfoScreen/FarmWorkInfoScreen.kt
  feature/main/src/main/java/kr/co/main/calendar/screen/farmWorkInfoScreen/FarmWorkInfoViewModel.kt
  feature/main/src/main/java/kr/co/main/model/calendar/DiaryStreakModel.kt
  feature/main/src/main/java/kr/co/main/navigation/CalendarNavGraph.kt
  feature/main/src/main/java/kr/co/main/navigation/MainNavigation.kt
  feature/main/src/main/java/kr/co/main/providers/calendar/FakeWorkDescriptionModelListProvider.kt
  feature/main/src/main/res/values/calendar_strings.xml
Labels: 🤖 android, 🛠️ refactor

#223 Fix: 챗봇 2번 주소 없을 때 막기
  feature/main/src/main/java/kr/co/main/home/chat/ChatViewModel.kt
Labels: 🐞 bug, 🤖 android

#224 Feature/community
  feature/main/src/main/java/kr/co/main/community/CommunityScreen.kt
  feature/main/src/main/java/kr/co/main/community/detail/BulletinDetailScreen.kt
  feature/main/src/main/java/kr/co/main/community/writing/BulletinWritingScreen.kt
Labels: 🐞 bug, 🤖 android, ✨ feat

#225 Feature/fcm
  app/src/main/java/kr/co/wdtt/nbdream/MainViewModel.kt
  core/data/src/main/java/kr/co/data/di/DataModule.kt
  core/data/src/main/java/kr/co/data/repository/AlarmRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/repository/FcmRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/source/local/SessionLocalDataSource.kt
  core/data/src/main/java/kr/co/data/source/remote/AlarmStatusDataSource.kt
  core/data/src/main/java/kr/co/data/source/remote/FcmRemoteDataSource.kt
  core/domain/src/main/java/kr/co/domain/repository/AlarmRepository.kt
  core/domain/src/main/java/kr/co/domain/repository/FcmRepository.kt
  core/domain/src/main/java/kr/co/domain/usecase/fcm/ExpireFcmTokenUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/fcm/FetchFcmTokenUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/fcm/SaveFcmTokenUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/notification/AlarmFetchUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/notification/AlarmUpdateUseCase.kt
  core/local/src/main/java/kr/co/local/SessionLocalDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/AlarmStatusRemoteDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/FcmRemoteDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/di/RemoteModule.kt
  feature/main/src/main/java/kr/co/main/model/my/MyPageNotificationSetting.kt
  feature/main/src/main/java/kr/co/main/my/setting/MyPageSettingViewModel.kt
  feature/main/src/main/java/kr/co/main/my/setting/notification/MyPageSettingNotificationRoute.kt
  feature/main/src/main/java/kr/co/main/my/setting/notification/MyPageSettingNotificationViewModel.kt
Labels: 🤖 android, 🛠️ refactor, ✨ feat

#228 Notification
  app/src/main/java/kr/co/wdtt/nbdream/MainActivity.kt
  app/src/main/java/kr/co/wdtt/nbdream/MainViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  core/data/src/main/java/kr/co/data/mapper/AlarmHistoryListMapper.kt
  core/data/src/main/java/kr/co/data/model/data/AlarmHistoryListData.kt
  core/data/src/main/java/kr/co/data/repository/AlarmRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/repository/FcmRepositoryImpl.kt
  core/data/src/main/java/kr/co/data/source/local/SessionLocalDataSource.kt
  core/data/src/main/java/kr/co/data/source/remote/AlarmStatusDataSource.kt
  core/domain/src/main/java/kr/co/domain/entity/AlarmHistoryEntity.kt
  core/domain/src/main/java/kr/co/domain/repository/AlarmRepository.kt
  core/domain/src/main/java/kr/co/domain/repository/FcmRepository.kt
  core/domain/src/main/java/kr/co/domain/usecase/alarm/AlarmFetchUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/alarm/AlarmUpdateUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/alarm/CheckAlarmHistoryUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/alarm/DeleteAlarmHistoryUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/alarm/GetAlarmHistoryUseCase.kt
  core/domain/src/main/java/kr/co/domain/usecase/fcm/FetchFcmTokenUseCase.kt
  core/local/src/main/java/kr/co/local/SessionLocalDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/AlarmStatusRemoteDataSourceImpl.kt
  core/remote/src/main/java/kr/co/remote/mapper/AlarmHistoryListRemoteMapper.kt
  core/remote/src/main/java/kr/co/remote/mapper/AlarmStatusRemoteMapper.kt
  core/remote/src/main/java/kr/co/remote/model/request/alarm/AlarmUpdateRequest.kt
  core/remote/src/main/java/kr/co/remote/model/request/fcm/AlarmUpdateRequest.kt
  core/remote/src/main/java/kr/co/remote/model/response/alarm/GetAlarmHistoryListResponse.kt
  core/remote/src/main/java/kr/co/remote/model/response/alarm/GetAlarmStatusResponse.kt
  core/ui/src/main/java/kr/co/ui/icon/dreamicon/Bellon.kt
  core/ui/src/main/res/drawable/img_notification_is_empty.xml
  feature/main/src/main/java/kr/co/main/home/HomeRoute.kt
  feature/main/src/main/java/kr/co/main/home/HomeViewModel.kt
  feature/main/src/main/java/kr/co/main/my/setting/notification/MyPageSettingNotificationRoute.kt
  feature/main/src/main/java/kr/co/main/my/setting/notification/MyPageSettingNotificationViewModel.kt
  feature/main/src/main/java/kr/co/main/navigation/MainNavigation.kt
  feature/main/src/main/java/kr/co/main/notification/NotificationRoute.kt
  feature/main/src/main/java/kr/co/main/notification/NotificationViewModel.kt
Labels: 🤖 android, 🛠️ refactor, ✨ feat
