Repository WDTT-CodingClub/NBDream, pull requests merged in 2024-05, with the labels that each got.

#7 PR 템플릿 만들기
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: 📝 docs

#10 기능추가 이슈 템플릿
  .github/ISSUE_TEMPLATE/Issue-feature-templet.yml
Labels: 🧦 chore

#11 기본 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/Bug-issue-template.yml
  .github/ISSUE_TEMPLATE/Design-issue-tamplete.yml
  .github/ISSUE_TEMPLATE/Refactoring_Template.yml
Labels: 🧦 chore

#20 기본 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/kr/co/wdtt/nbdream/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/wdtt/nbdream/ui/BaseViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainActivity.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Color.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Theme.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/kr/co/wdtt/nbdream/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 🤖 android, ✨ feat, ⚙️ setting

#69 Feature/theme
  .idea/appInsightsSettings.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/AccountBookEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarDiaryEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarScheduleEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarTopicEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Color.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Paddings.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Theme.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Type.kt
Labels: 🤖 android, ✨ feat, ⚙️ setting

#70 복수 API 설정 및 베이스 Mapper
  .idea/deploymentTargetSelector.xml
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle.kts
  app/src/main/java/kr/co/wdtt/core/domain/base/BaseMapper.kt
  app/src/main/java/kr/co/wdtt/core/ui/base/BaseViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/di/NetworkModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/di/RepositoryModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/EntityWrapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/WeatherForecastMapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/api/NetworkApi.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/dto/WeatherForecastResponse.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/model/ApiResponse.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/model/ApiResult.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/model/NetWorkRequestInfo.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/model/RequestType.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/HeaderParser.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/INetworkFactoryManager.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetWorkRequestFactory.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkFactoryManager.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkService.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/StringConverterFactory.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/WeatherForecastRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/di/UsecaseModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/WeatherForecastEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/WeatherForecastRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetDayWeatherForecast.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/IGetDayWeatherForecast.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/home/HomeRoute.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/home/HomeViewModel.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🤖 android, ✨ feat

#71 캘린더 화면 도메인 레이어 설계 (+ 데이터 레이어 일부 작업)
  app/build.gradle.kts
  app/src/main/java/kr/co/wdtt/nbdream/data/di/NetworkModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/di/RepositoryModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/FarmWorkMapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/WeatherForecastMapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/dto/FarmWorkResponse.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/INetworkFactoryManager.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkFactoryManager.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkFactoryManagerImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/FarmWorkRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/WeatherForecastRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/di/UsecaseModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarDiaryEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarScheduleEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarTopicEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/DreamCrop.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/DreamImage.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/FarmWorkEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/HolidayEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/ScheduleEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/WorkDiaryEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/FarmWorkRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/HolidayRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/ScheduleRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/WorkDiaryRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetDayWeatherForecast.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetDayWeatherForecastImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/IGetDayWeatherForecast.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/home/HomeViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🤖 android, ✨ feat, 🖥 server

#72 kotlinx serialization plugin 다시 추가
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: 🤖 android, ⚙️ setting, 🖥 server

#79 Feat: 확장자 추가/ Base viewmodel 로딩 스코프 추가
  app/src/main/java/kr/co/wdtt/core/ui/base/BaseViewModel.kt
  app/src/main/java/kr/co/wdtt/core/ui/ext/ModifierExt.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/home/HomeViewModel.kt
Labels: 🤖 android

#78 Feat: 로그인 부분의 UserEntity 작성
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/UserEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/theme/Color.kt
  app/src/main/res/drawable/img_google_login.png
  app/src/main/res/drawable/img_kakao_login.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/drawable/img_naver_login.png
Labels: 🤖 android, ✨ feat

#80 Design: Login UI 작성
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainActivity.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/home/HomeRoute.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/home/HomeViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/onboarding/login/Login.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/onboarding/login/LoginSplash.kt
  app/src/main/res/values/strings.xml
Labels: 🤖 android, 🎨design

#81 캘린더 화면 도메인 작업 (설계 수정 & UseCase 추가) + 데이터 레이어 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/wdtt/nbdream/data/di/RepositoryModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/HolidayMapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/api/NetworkApi.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/dto/HolidayResponse.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkFactoryManager.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/NetworkFactoryManagerImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/retrofit/StringConverterFactory.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/FarmWorkRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/HolidayRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/WeatherForecastRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/di/UsecaseModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/CalendarDateEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/HolidayEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/ScheduleEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/WorkDiaryEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/HolidayRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetCalendarDate.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetCalendarDateImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetFarmWork.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetFarmWorkImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetHoliday.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/GetHolidayImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/calendar/CalendarScreen.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/calendar/CalendarViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/home/HomeViewModel.kt
  app/src/main/res/xml/network_security_config.xml
Labels: 🤖 android, ✨ feat

#84 Feat: Token저장 DataStore생성
  app/build.gradle.kts
  app/src/main/java/kr/co/wdtt/core/data/source/local/SessionLocalDataSource.kt
  app/src/main/java/kr/co/wdtt/core/local/SessionLocalDataSourceImpl.kt
  app/src/main/java/kr/co/wdtt/core/local/di/LocalModule.kt
  app/src/main/java/kr/co/wdtt/core/local/di/LocalServiceModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  gradle/libs.versions.toml
Labels: 🧦 chore, 🤖 android

#82 Feat: AccountBookEntity 타입 변경 및 sendRequest 매개변수 추가
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/AccountBookMapper.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/api/NetworkApi.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/remote/dto/AccountBookResponse.kt
  app/src/main/java/kr/co/wdtt/nbdream/data/repository/AccountBookRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/entity/AccountBookEntity.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/repository/AccountBookRepository.kt
  app/src/main/res/values/accountbook_strings.xml
Labels: 🤖 android, ✨ feat, 🖥 server

#86 Refactor: AccountBookMapper 수정
  app/src/main/java/kr/co/wdtt/nbdream/data/mapper/AccountBookMapper.kt
Labels: 🤖 android, ✨ feat

#89 Feat: Ktor api연결 설정
  app/build.gradle.kts
  app/src/main/java/kr/co/wdtt/core/remote/di/NetworkModule.kt
  app/src/main/java/kr/co/wdtt/core/remote/model/PostAuthRefreshResponse.kt
  app/src/main/java/kr/co/wdtt/core/ui/base/BaseViewModel.kt
  gradle/libs.versions.toml
Labels: 🤖 android, ✨ feat, ⚙️ setting

#90 로그인 확인 후 네비게이션 설정
  app/build.gradle.kts
  app/src/main/java/kr/co/wdtt/core/data/DataModule.kt
  app/src/main/java/kr/co/wdtt/core/data/SessionRepositoryImpl.kt
  app/src/main/java/kr/co/wdtt/core/domain/SessionRepository.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/auth/FetchAuthUseCase.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/auth/FetchAuthUseCaseImpl.kt
  app/src/main/java/kr/co/wdtt/nbdream/domain/usecase/di/UseCaseModule.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/DreamApp.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/MainViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/MainRoute.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/calendar/CalendarScreen.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/calendar/CalendarViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/community/BulletinDetailScreen.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/community/BulletinWritingScreen.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/community/CommunityScreen.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/community/CommunityViewModel.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/main/navigation/MainNavigation.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/onboarding/OnBoardRoute.kt
  app/src/main/java/kr/co/wdtt/nbdream/ui/onboarding/navigation/OnBoardNavigation.kt
  gradle/libs.versions.toml
Labels: 🤖 android, ✨ feat
